name: event_manager_flutter
description: A simple event management Flutter app with host and attendee sides.
publish_to: 'none'
version: 0.0.1
environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  image_picker: ^1.2.1
  intl: ^0.18.0
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  http: ^1.6.0
  uuid: ^4.5.2
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  mobile_scanner: ^7.1.4
  qr_flutter: ^4.1.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/ 



flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  # Additional iOS options (optional):
  # ios: true
  # image_path_ios: "assets/icons/app_icon_ios.png"
  # Additional Android options (optional):
  # image_path_android: "assets/icons/app_icon_android.png"
  # min_sdk_android: 21  # Minimum Android SDK version